Wr/package1 version create
forcedotcom/packaging pull request #10
Opened 2022-07-28 21:33 UTC by WillieRuemmele

@W-10833096@

adds a method to create a 1gp package upload request for `package1:version:create`
refactors tests
allows `.test.ts` extension to be run with `yarn test`

2022-07-28 22:01 UTC, peternhale requested changes

2022-07-29 14:51 UTC, peternhale approved these changes

2022-07-29 21:31 UTC, shetzel requested changes

2022-07-29 21:31 UTC, shetzel commented on .sfdevrc.json
> +    "testsPath": "test/**/*est.ts"
it's better to just have 1 pattern.  Let's only support *.test.ts.  That is pretty much universal in our plugins.

2022-07-29 21:31 UTC, shetzel commented on src/interfaces/packagingInterfacesAndType.ts
> +>;
Are all of these fields required to create a package1 version?  I suspect not.  I think you'll have to do an intersection of the required fields and optional fields.  something like:
`Partial<Pick<PackagingSObjects.PackageUploadRequest, {optional_fields}>> & Pick<PackagingSObjects.PackageUploadRequest, {required_fields}>`

2022-07-29 21:31 UTC, shetzel commented on src/package1/package1VersionCreate.ts
> +  pollingOptions = { frequency: Duration.seconds(5), timeout: Duration.seconds(0) }
It'll be a better API if it supports both `number` and `Duration` as polling options.  We don't have to change this now but I'd want the GA version to handle that.  I have a version of it in my branch if you're interested.

2022-07-29 21:31 UTC, shetzel commented on src/package1/package1VersionCreate.ts
> +      .retrieve(createRequest.id)) as unknown as PackagingSObjects.PackageUploadRequest;
Yeah, I saw this too.  We should try to fix this in jsforce because this is not great.

2022-07-29 21:31 UTC, shetzel commented on src/package1/package1VersionCreate.ts
> +    return pollingClient.subscribe<PackagingSObjects.PackageUploadRequest>();
What happens when the pollingClient times out?  It'll throw an error but not return the last known status of the request, which can be pretty useful.  We need some common patterns to follow for polling so it's handled consistently, including emitting events, polling options, and error handling.

2022-07-29 21:31 UTC, shetzel commented on test/package1/package1VersionCreate.test.ts
> +        // @ts-ignore - to avoid stubbing every property of sobject
jsyk, ts-sinon handles this nicely.  I think it's `stubInterface` or something like that.

2022-07-29 21:31 UTC, shetzel commented on test/package1/package1VersionList.test.ts
> +  // const $$ = testSetup();
should this commented code be removed?

2022-07-29 22:23 UTC, shetzel approved these changes

2022-07-29 22:23 UTC, merged