Wr/package installed list
forcedotcom/packaging pull request #14
Opened 2022-08-08 17:11 UTC by WillieRuemmele

@W-11542978@

adds query for `package:installed:list` command
changes NUT to use lib instead of command

2022-08-08 17:29 UTC, peternhale requested changes

2022-08-08 17:29 UTC, peternhale commented on src/interfaces/packagingSObjects.ts
> +  export type InstalledPackage = {
@WillieRuemmele this structure does not look like the [public docs](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_installedpackage.htm).

The query that is using this looks like it is get data from relationship. I think this type belongs in `[packagingInterfacesAndType.ts](https://github.com/forcedotcom/packaging/blob/wr/packageInstalledList/src/interfaces/packagingInterfacesAndType.ts)`

2022-08-09 14:03 UTC, peternhale approved these changes

2022-08-09 21:40 UTC, mshanemc commented
[fyi: fixed some conflicts and bumped ts-node to solve build errors]

QA notes:
✅ -h and --help work
❌  the sfdx command has some examples and this one doesn't. maybe use `examples` instead of `help` prop

👎🏻 one long-named package makes the whole table awful.   Any chance new oclif table can be smarter with truncate
![Screen Shot 2022-08-09 at 4 28 15 PM](https://user-images.githubusercontent.com/4261788/183764994-e99362d4-8dca-489c-8fcc-e6069f511c4d.png)

🏆 works without a project!  That's such a big improvement!!

✅ json matches sfdx, including the "null" behavior

2022-08-10 15:59 UTC, merged