feat: adds support for seed metadata to both the convert and package version create commands
forcedotcom/packaging pull request #203
Opened 2023-01-25 01:26 UTC by tshopshireSalesforce

What does this PR do?

Adds optional seedMetadata so unpackageable metadata can be pushed to the build org that the packaged metadata depends on, such as StandardValueSets.
What issues does this PR fix or reference?

[W-12204966](https://gus.my.salesforce.com/a07EE00001HEshUYAT)

2023-01-25 17:47 UTC, ganeshnt approved these changes

2023-01-25 18:38 UTC, ganeshnt approved these changes

2023-01-25 23:00 UTC, shetzel requested changes

2023-01-26 00:14 UTC, tshopshireSalesforce commented on src/package/packageConvert.ts
> +    process.stdout.write('hasSeed');
Nice catch. Somehow slipped by me.

2023-01-26 00:19 UTC, tshopshireSalesforce commented on src/package/packageVersionCreate.ts
> +export namespace PackageVersionCreateUtil {
I was hitting an issue as I was not able to mock the private methods that the public method were calling correctly in the unit test. I don't think it makes sense for the convert code to need to instantiate a PackageVersionCreate in order to call these utility methods. Do you have an example I can see of how the private methods can be manipulated? Regardless, I think it makes sense for the resolveMetadata method to be exposed here, unless there is a better way to share the logic between the two?

2023-01-26 18:39 UTC, closed without merging