feat: add package1Display method for use with package1:version:displa…
forcedotcom/packaging pull request #5
Opened 2022-07-06 20:44 UTC by WillieRuemmele

…y command

@W-10833140@

adds `package1Display` method for querying org for package1 commands - https://github.com/salesforcecli/plugin-packaging/pull/26

2022-07-06 21:19 UTC, peternhale requested changes

2022-07-06 21:19 UTC, peternhale commented on src/package1/packageDisplay.ts
> +  const query = `SELECT Id,MetadataPackageId,Name,ReleaseState,MajorVersion,MinorVersion,PatchVersion,BuildNumber FROM MetadataPackageVersion WHERE id = '${id}'`;
@WillieRuemmele Could you create `MetadataPackageVersion` type and expose it in /src/interfaces/packagingSobject.ts.

2022-07-06 21:19 UTC, peternhale commented on src/package1/packageDisplay.ts
> +  const results = (await connection.tooling.query(query)).records;
Then the type can be added to the query 
``` suggestion
  const results = (await connection.tooling.query<PackagingSobjects.MetadataPackageVersion>(query)).records;
```

2022-07-06 21:19 UTC, peternhale commented on src/package1/packageDisplay.ts
> +export type Package1Display = {
Would you move this to src/interfaces/packagingInterfacesAndType.ts

2022-07-07 11:44 UTC, peternhale approved these changes

2022-07-15 23:30 UTC, mshanemc commented on src/package1/packageDisplay.ts
> +}
```suggestion
  return results.map((result) => ({
      MetadataPackageVersionId: result.Id,
      MetadataPackageId: result.MetadataPackageId,
      Name: result.Name,
      ReleaseState: result.ReleaseState,
      Version: `${result.MajorVersion}.${result.MinorVersion}.${result.PatchVersion}`,
      BuildNumber: result.BuildNumber,
  }));
}
```

2022-07-19 13:24 UTC, merged