fix: move verbose field to default fields
forcedotcom/packaging pull request #548
Opened 2024-04-16 17:29 UTC by mradulsf

Move the non-CodeCoverage fields from the verbose query to the default query so that JSON responses are more accurate.

@W-15398724@

2024-04-16 22:37 UTC, SagarBijjam reviewed
@mradulsf  the WI mentioned about similarly affected packaging commands. have you come across any. Like `package:version:create:report` command that have similar fields

2024-04-17 15:10 UTC, mradulsf commented
@SagarBijjam Yes, I made change to another file for package version report. Is that not the one you are talking about?

2024-04-17 21:31 UTC, shetzel requested changes
You need to update `packageTest.nut.ts` line 279 to now expect the `Id` as a property of the returned result since you added it to the query.
In other words, it should now be:
`expect(result).to.have.property('Id');`

Our preference is to test public APIs rather than exposing a private function and unit testing that.

2024-04-18 15:08 UTC, SagarBijjam commented
> @SagarBijjam Yes, I made change to another file for package version report. Is that not the one you are talking about?

I was referring to `package:version:create:report`, but it seems that the command doesn't have similar verbose fields. So skip it

2024-04-18 17:14 UTC, shetzel approved these changes

2024-04-18 17:27 UTC, SagarBijjam approved these changes

2024-04-18 22:02 UTC, merged