package1 refactor
forcedotcom/packaging pull request #61
Opened 2022-09-28 20:14 UTC by WillieRuemmele

@W-11825243@

refactors `Package1` to `Package1Version` because it only deals with 1gp package versions
moves all methods into a class
adds some UTs for invalid IDs
adds ID validation

2022-09-29 12:25 UTC, peternhale requested changes

2022-09-29 12:25 UTC, peternhale commented on src/package1/package1Version.ts
> +    const createRequest = await this.connection.tooling.sobject('PackageUploadRequest').create(options);
The create is blindly using the options as crafted by the caller. I understand that the plugin command is vetting the inputs, but if used by an API consumer is the exception thrown by the tooling create sufficient to properly guide the caller to the mistake in input values?

2022-09-29 12:25 UTC, peternhale commented on src/package1/package1Version.ts
> +    return results.map((result) => ({
Why not return the entire object. This function's use is no longer tied to just one CLI command.

2022-09-29 12:25 UTC, peternhale commented on src/package1/package1Version.ts
> +  public static async display(connection: Connection, id: string): Promise<Package1Display[]> {
Consider a different name for this function, maybe `getPackageVersion`

2022-09-29 12:25 UTC, peternhale commented on src/package1/package1Version.ts
> +  public async create(
Should probably be static. This function is creating a new 04t, which is what package1Version is supposed to represent.

2022-09-29 12:25 UTC, peternhale commented on src/package1/package1Version.ts
> +  private async packageUploadPolling(id: string, timeout: number, frequency: number): Promise<StatusResult> {
Should be static

2022-09-29 12:25 UTC, peternhale commented on src/package1/package1Version.ts
> +    return queryResult.records?.map((record) => ({
Return all of a MetadataPackageVersion. Caller will decide which fields to use.

2022-09-29 12:25 UTC, peternhale commented on src/package1/package1Version.ts
> +  public static async display(connection: Connection, id: string): Promise<Package1Display[]> {
This function should not static. Caller knows the ID so
```
const p1v = new Package1Version(id, connection);
const p1vData = p1v.getPackageVersion();
...
```

2022-09-30 14:40 UTC, peternhale requested changes
Looks good @WillieRuemmele, just a minor tweak to consider.

2022-09-30 14:40 UTC, peternhale commented on src/package1/package1Version.ts
> +  public constructor(private connection: Connection) {}
Please add id to c'tor.

2022-09-30 14:40 UTC, peternhale commented on src/package1/package1Version.ts
> +  public async getPackageVersion(id: string): Promise<MetadataPackageVersion[]> {
Instance method can use id field, so id can be removed from this getter

2022-09-30 18:10 UTC, shetzel approved these changes
Just questions and nits.

2022-09-30 18:10 UTC, shetzel commented on src/package1/package1Version.ts
> +  public constructor(private connection: Connection, private id: string) {
Can this also be an alias or only ID?

2022-09-30 18:10 UTC, shetzel commented on src/package1/package1Version.ts
> +   * Executes server-side logic for the package1:display command
Please change the comment from command specific to what it does and returns.

2022-09-30 18:10 UTC, shetzel commented on src/utils/versionNumber.ts
> +  public static parseMajorMinor(versionString: string): { major: number; minor: number } {
Add jsdoc.

2022-09-30 19:12 UTC, WillieRuemmele commented on src/package1/package1Version.ts
> +  public constructor(private connection: Connection, private id: string) {
no aliases for package1

2022-09-30 19:20 UTC, peternhale approved these changes

2022-10-03 20:03 UTC, merged